# Generated by Django 3.2.6 on 2021-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210915_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='toktom',
            field=models.TextField(blank=True, null=True),
        ),
    ]
